const $=id=>document.getElementById(id),CFG=window.DASHBOARD_CONFIG||{},fmt=n=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:1}).format(CC.number(n)),rp=n=>'Rp '+new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}).format(CC.number(n));
const esc=s=>String(s??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const months=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
const monthLabel=m=>{const match=/^(\d{4})-(\d{2})$/.exec(m);return match?months[+match[2]-1]+' '+match[1]:m;};
let DATA=null,busy=false,installPrompt=null,currentPage='overview';
function read(key){try{return localStorage.getItem(key);}catch{return null;}}
function write(key,value){try{localStorage.setItem(key,value);return true;}catch{return false;}}
function notice(message,type=''){const el=$('notice');el.textContent=message;el.className='notice '+type;}
function api(){return read('ccLogistikApiV3')||CFG.API_URL||'';}
function validApi(url){try{const u=new URL(url);return u.protocol==='https:'&&u.hostname==='script.google.com'&&/^\/macros\/s\/[^/]+\/exec$/.test(u.pathname);}catch{return false;}}
function setBusy(value){busy=value;$('refreshBtn').disabled=value;$('refreshBtn').classList.toggle('busy',value);$('refreshBtn').textContent=value?'↻ Menghubungkan…':'↻ Muat Ulang';}
function jsonp(url,force){return new Promise((resolve,reject)=>{
  const cb='ccLogistik'+Date.now()+Math.random().toString(36).slice(2),script=document.createElement('script');let settled=false;
  const cleanup=()=>{clearTimeout(timer);script.remove();window[cb]=()=>{};setTimeout(()=>delete window[cb],60000);};
  const fail=message=>{if(settled)return;settled=true;cleanup();reject(new Error(message));};
  const timer=setTimeout(()=>fail('Koneksi melewati 25 detik. Coba buka URL /exec langsung atau gunakan jaringan lain.'),25000);
  window[cb]=res=>{if(settled)return;settled=true;cleanup();res&&res.ok&&res.data?resolve(res.data):reject(new Error(res?.error||'Respons API tidak sesuai. Pastikan Code.gs V3 sudah di-deploy.'));};
  script.onerror=()=>fail('Browser gagal mengakses Apps Script. Jika Incognito bisa, periksa ekstensi atau sesi akun Chrome.');
  const target=new URL(url);target.searchParams.set('callback',cb);target.searchParams.set('refresh',force?'1':'0');target.searchParams.set('t',Date.now());script.src=target.href;document.head.append(script);
});}
function validateData(d){if(!d||!Array.isArray(d.orders)||!d.meta)throw new Error('Format data tidak sesuai. Gunakan backend V3 atau V2 GitHub.');}
async function load(force=false){
  if(busy)return;if(!validApi(api())){notice('API belum dihubungkan. Klik Koneksi dan tempel URL Apps Script /exec.','error');$('connection').textContent='Belum dikonfigurasi';return;}
  setBusy(true);notice(DATA?'Memperbarui data tanpa menutup dashboard…':'Mengambil data Spreadsheet…');
  try{const d=await jsonp(api(),force);validateData(d);DATA=d;write('ccLogistikCacheV3',JSON.stringify({api:api(),data:d}));renderFilters();render();$('updated').textContent='Data dibaca: '+d.meta.updatedAt;$('connection').textContent='● Terhubung';notice('Terhubung. Pembaruan otomatis setiap '+(Number(CFG.REFRESH_MINUTES)||5)+' menit.');}
  catch(e){$('connection').textContent=DATA?'● Data terakhir':'● Koneksi gagal';notice(e.message+(DATA?' Data terakhir tetap ditampilkan; bukan data live.':''),DATA?'offline':'error');}
  finally{setBusy(false);}
}
function renderFilters(){const old=$('monthFilter').value,keys=[...new Set(DATA.orders.map(x=>x.month))].sort();$('monthFilter').innerHTML='<option value="all">Semua Periode</option>'+keys.map(k=>'<option value="'+esc(k)+'">'+esc(monthLabel(k))+'</option>').join('');if(keys.includes(old))$('monthFilter').value=old;const selected=$('itemFilter').value,items=[...new Set((DATA.salesItems||[]).map(x=>x.item))];$('itemFilter').innerHTML=items.map(x=>'<option>'+esc(x)+'</option>').join('');if(items.includes(selected))$('itemFilter').value=selected;}
function rows(){return DATA?CC.filterOrders(DATA,$('monthFilter').value,$('search').value):[];}
function periodRows(a){const period=$('monthFilter').value;if(period==='all')return a;const name=months[Number(period.slice(5))-1].toLowerCase();return a.filter(x=>String(x.month).toLowerCase().replace(/2$/,'').trim().startsWith(name));}
function table(id,data,cols){if(!data.length){$(id).innerHTML='<div class="empty">Tidak ada data pada filter ini.</div>';return;}$(id).innerHTML='<table><thead><tr>'+cols.map(c=>'<th>'+c[0]+'</th>').join('')+'</tr></thead><tbody>'+data.map(x=>'<tr>'+cols.map(c=>{let v=x[c[1]],t=c[2];v=v===null||v===undefined?'—':t==='rp'?rp(v):t==='n'?fmt(v):t==='pct'?fmt(v)+'%':v;return '<td class="'+(t?'num':'')+'">'+esc(v)+'</td>';}).join('')+'</tr>').join('')+'</tbody></table>';}
function render(){
  if(!DATA){document.querySelectorAll('.table-wrap,.chart').forEach(el=>el.replaceChildren());$('alerts').replaceChildren();$('updated').textContent='Belum memuat data dari koneksi ini.';$('kpis').innerHTML='<article class="card empty">Hubungkan API melalui tombol Koneksi untuk menampilkan data.</article>';return;}
  const a=rows(),k=CC.kpi(a),ranking=CC.outlets(a),trend=CC.monthly(a),type=$('chartType').value;
  $('kpis').innerHTML=[['Nilai Invoice',k.invoice,rp],['Pembayaran',k.paid,rp],['Selisih Pembayaran',k.balance,rp],['Jumlah Order',k.orders,fmt],['Outlet Aktif',k.outlets,fmt],['Rasio Pembayaran',k.rate,n=>fmt(n)+'%']].map(([name,n,f])=>'<article class="kpi"><small>'+name+'</small><strong data-target="'+n+'">'+f(n)+'</strong><p>Mengikuti filter order aktif</p></article>').join('');
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelectorAll('.kpi strong').forEach((el,i)=>{const f=i<3?rp:i===5?n=>fmt(n)+'%':fmt,target=Number(el.dataset.target),start=performance.now();function tick(now){const p=Math.min(1,(now-start)/550);if(!el.isConnected)return;el.textContent=f(target*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(tick);}requestAnimationFrame(tick);});}
  const alertList=[];if(k.balance>0)alertList.push({title:'Selisih belum dibayar',text:rp(k.balance)+' berdasarkan filter order.',level:'danger'});const bad=a.filter(x=>x.leadDays!==null&&x.leadDays<0);if(bad.length)alertList.push({title:'Periksa tanggal pengiriman',text:bad.length+' estimasi kirim mendahului tanggal order.',level:'warning'});if(!alertList.length)alertList.push({title:'Tidak ada selisih utama',text:'Berdasarkan order yang sedang ditampilkan.',level:'success'});$('alerts').innerHTML=alertList.map(x=>'<div class="alert '+x.level+'"><b>'+x.title+'</b>'+x.text+'</div>').join('');
  const cols=[['Outlet','outlet'],['Order','orders','n'],['Invoice','invoice','rp'],['Dibayar','paid','rp'],['Selisih','balance','rp']];table('rankingTable',ranking.slice(0,10),cols);table('outletTable',ranking,cols);table('orderTable',a,[['Tanggal','orderDate'],['Periode Sumber','sheet'],['Outlet','outlet'],['Invoice','invoice','rp'],['Dibayar','paid','rp'],['Selisih','balance','rp'],['Estimasi Kirim','deliveryDate'],['Lead Time (hari)','leadDays','n']]);
  drawChart('monthlyChart',trend.map(x=>monthLabel(x.month)),[{name:'Invoice',color:'#1570ef',values:trend.map(x=>x.invoice)},{name:'Pembayaran',color:'#12b76a',values:trend.map(x=>x.paid)}],{type,format:rp,onSelect:i=>{$('monthFilter').value=trend[i].month;render();}});
  drawChart('outletChart',ranking.slice(0,8).map(x=>x.outlet),[{name:'Invoice',color:'#1570ef',values:ranking.slice(0,8).map(x=>x.invoice)}],{type,format:rp,onSelect:i=>{$('search').value=ranking[i].outlet;render();}});
  const production=periodRows(DATA.production||[]);table('productionTable',production,[['Bulan','month'],['Box','boxes','n'],['Berat (kg)','kg','n'],['kg/orang','kgPerson','n'],['kg/jam','kgHour','n'],['Kategori','category']]);
  drawChart('productionChart',production.map(x=>x.month),[{name:'Box produksi',color:'#ef3e42',values:production.map(x=>x.boxes)}],{type,format:fmt});drawChart('productivityChart',production.map(x=>x.month),[{name:'kg/jam (sumber)',color:'#ef3e42',values:production.map(x=>x.kgHour)}],{type,format:fmt});
  const inventory=periodRows(DATA.inventory||[]);table('inventoryTable',inventory,[['Periode','month'],['Bahan','item'],['Masuk','incoming','n'],['Keluar','outgoing','n'],['Stok Akhir','closing','n'],['Selisih Fisik','variance','n']]);drawChart('inventoryChart',inventory.map(x=>x.month+' '+x.item),[{name:'Masuk (satuan sumber)',color:'#1570ef',values:inventory.map(x=>x.incoming)},{name:'Keluar (satuan sumber)',color:'#ef3e42',values:inventory.map(x=>x.outgoing)}],{type,format:fmt});
  const sales=periodRows((DATA.salesItems||[]).filter(x=>x.item===$('itemFilter').value));table('salesTable',sales,[['Barang','item'],['Bulan','month'],['Qty','qty','n']]);drawChart('salesChart',sales.map(x=>x.month),[{name:'Qty '+($('itemFilter').value||''),color:'#1570ef',values:sales.map(x=>x.qty)}],{type,format:fmt});
  table('priceTable',periodRows(DATA.prices||[]),[['Bahan','item'],['Bulan','month'],['Harga','price','rp'],['Label Sumber','status']]);
}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
$('csvBtn').onclick=()=>{if(!DATA)return;const csv=[['Tanggal','Outlet','Invoice','Dibayar','Selisih'],...rows().map(x=>[x.orderDate,x.outlet,x.invoice,x.paid,x.balance])].map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""').replace(/^[=+@-]/,"'$&")+'"').join(';')).join('\r\n');download(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),'CC_Logistik_Order.csv');};
document.querySelectorAll('.chart-save').forEach(b=>b.onclick=()=>{const svg=$(b.dataset.chart).querySelector('svg');if(svg){const copy=svg.cloneNode(true);copy.setAttribute('xmlns','http://www.w3.org/2000/svg');download(new Blob([copy.outerHTML],{type:'image/svg+xml'}),'CC_Logistik_Grafik.svg');}});
function closeNav(){document.body.classList.add('nav-closed');write('ccNavClosed','1');}function openNav(){document.body.classList.remove('nav-closed');write('ccNavClosed','0');}
$('closeMenu').onclick=closeNav;$('openMenu').onclick=openNav;$('overlay').onclick=closeNav;
const titles={overview:'Ringkasan Logistik',orders:'Order & Mitra',inventory:'Persediaan',production:'Produksi',sales:'Pemakaian Barang',prices:'Harga Bahan'};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{currentPage=b.dataset.page;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===currentPage));$('pageTitle').textContent=titles[currentPage];if(innerWidth<=760)closeNav();render();});
['monthFilter','chartType','itemFilter'].forEach(id=>$(id).onchange=render);let searchTimer;$('search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(render,200);};$('resetBtn').onclick=()=>{$('monthFilter').value='all';$('search').value='';render();};$('refreshBtn').onclick=()=>load(true);
$('settingsBtn').onclick=()=>{$('apiInput').value=validApi(api())?api():'';$('settings').showModal();};$('cancelSettings').onclick=()=>$('settings').close();$('settingsForm').onsubmit=e=>{e.preventDefault();const value=$('apiInput').value.trim();if(!validApi(value)){notice('URL harus https://script.google.com/macros/s/…/exec','error');return;}if(!write('ccLogistikApiV3',value)){notice('Browser tidak mengizinkan penyimpanan pengaturan. Aktifkan penyimpanan situs.','error');return;}DATA=null;$('settings').close();render();load(true);};
addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});$('installBtn').onclick=async()=>{if(installPrompt){await installPrompt.prompt();const choice=await installPrompt.userChoice;installPrompt=null;if(choice.outcome==='accepted')notice('Permintaan pemasangan aplikasi diterima browser.');}else $('installDialog').showModal();};$('closeInstall').onclick=()=>$('installDialog').close();addEventListener('appinstalled',()=>notice('Aplikasi berhasil dipasang.'));
if('serviceWorker' in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(()=>notice('Mode offline belum aktif; dashboard online tetap dapat digunakan.','offline'));
if(innerWidth<=760||read('ccNavClosed')==='1')closeNav();
try{const cache=JSON.parse(read('ccLogistikCacheV3')||'null');if(cache&&cache.api===api()){validateData(cache.data);DATA=cache.data;renderFilters();$('updated').textContent='Data tersimpan: '+DATA.meta.updatedAt;}}catch{/* cache rusak diabaikan */}
render();load();setInterval(()=>{if(!document.hidden&&navigator.onLine)load(false);},Math.max(1,Number(CFG.REFRESH_MINUTES)||5)*60000);addEventListener('online',()=>load(false));addEventListener('offline',()=>notice('Koneksi internet terputus. Data terakhir ditampilkan jika tersedia.','offline'));
